### ISSUE TITLE
Matrix looping issue

### ISSUE THREAD

**Issue by mathieugouin** [aneagoie/ztm-python-cheat-sheet#16]
Hello, very nice cheat sheet by the way :) 

I just found a small bug:

```
# Looping through a matrix by rows:
mx = [[1,2],[3,4]]
for row in range(len(mx)):
	for col in range(len(mx)):
		print(mx[row][col]) # 1 2 3 4
```

The column for loop should be like this:

`for col in range(len(mx[0])):
`

It works by chance, because you matrix is 2 x 2 :)

**Comment by mathieugouin** [comment]
Same here:

```
# Transform into a list:
[mx[row][col] for row in range(len(mx)) for col in range(len(mx[0]))] # [1,2,3,4]

```

**Comment by aneagoie** [comment]
Thanks for catching this one! Would you mind submitting a pull request so you get the credit for the change?

**Comment by mathieugouin** [comment]
Sure no problem!

Mathieu

**Comment by mathieugouin** [comment]
Refer to PR #17.

Thanks!
