### ISSUE TITLE
Spelling Error

### ISSUE THREAD

**Issue by orangepaw3** [aneagoie/ztm-python-cheat-sheet#6]
I know this is likely a silly "issue" post, but, here it is:
[](https://nicedoc.io/aneagoie/ztm-python-cheat-sheet#ordereddict)
https://nicedoc.io/aneagoie/ztm-python-cheat-sheet#ordereddict (if the link didn't work)

When you click/goto this link, you will see "respoded" should be "responded."

Have a good day.

**Comment by aneagoie** [comment]
Sorry I missed this until now. Just fixed it :)
